theme: jekyll-theme-cayman

title: "Special Session on Machine Learning for Wireless Communication Systems"

description: International Joint Conference on Neural Networks (IJCNN) at WCCI 2022

github:
  is_project_page: false
